JavaScript: true

engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
      import/extensions:
        enabled: false
    extensions:
    - .js
    - .jsx
  scss-lint:
    enabled: true