version: "2"
checks:
  file-lines:
    enabled: false # default is 250, which is low when we have logic and ui in some files
  method-lines:
    enabled: false # default is 25 which is low for render() methods
plugins:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
  # eslint:
  #   enabled: true
  #   channel: "eslint-6"
  #   checks:
  #     import/no-unresolved:
  #       enabled: false
  #     import/extensions:
  #       enabled: false
  #     no-loops/no-loops:
  #       enabled: false
  #   config:
  #     extensions:
  #     - .js
  #     - .jsx
  # scss-lint:
  #   enabled: true
exclude_patterns:
- node_modules/
- build/ # build artifacts
- config/ # build configuration	- config/ # build configuration
- coverage/ # test coverage
- scripts/ # build & utility scripts
- src/__mocks__/ # test objects
- src/Constants/PropTypes.js # shape definitions
