const bidListObject = {
  count: 3,
  next: null,
  previous: null,
  results: [
    {
      id: 3,
      user: 'rehmant',
      position_info: {
        id: 11,
        position: {
          grade: '03',
          skill: 'POLITICAL AND ECONOMIC AFFAIRS (6050)',
          position_number: '10035561',
          title: 'POLITICAL/ECONOMIC OFFICER',
          create_date: '2015-08-05',
          update_date: '2017-06-08',
          bureau: '(AF) BUREAU OF AFRICAN AFFAIRS',
          post: {
            id: 199,
            location: {
              id: 103,
              country: 'Sierra Leone',
              code: '00A',
              city: 'Freetown',
              state: '',
            },
          },
        },
        bidcycle: {
          name: 'Demo BidCycle 2017-10-31 16:00:51.254762',
        },
        bid_statistics: [
          {
            id: null,
            total_bids: 0,
            in_grade: 0,
            at_skill: 0,
            in_grade_at_skill: 0,
            has_handshake_offered: false,
            has_handshake_accepted: null,
          },
        ],
      },
      status: 'approved',
      draft_date: '2017-12-20',
      submitted_date: '2017-12-20',
      handshake_offered_date: '2017-12-20',
      handshake_accepted_date: '2017-12-20',
      handshake_declined_date: '2017-12-20',
      in_panel_date: '2017-12-20',
      scheduled_panel_date: '2017-12-20',
      approved_date: '2017-12-20',
      declined_date: '2017-12-20',
      closed_date: '2017-12-20',
      create_date: '2017-12-20',
      update_date: '2017-12-20',
      is_priority: false,
      reviewer: {
        username: 'woodwardw',
        first_name: 'Wendy',
        last_name: 'Woodward',
        email: 'woodwardw@state.gov',
        phone_number: '555-555-5555',
        is_cdo: false,
      },
    },
    {
      id: 1,
      user: 'rehmant',
      position_info: {
        position: {
          id: 1,
          grade: '05',
          skill: 'OFFICE MANAGEMENT (9017)',
          position_number: '00003026',
          title: 'OMS (COM)',
          create_date: '2006-09-20',
          update_date: '2017-06-08',
          bureau: '(AF) BUREAU OF AFRICAN AFFAIRS',
          post: {
            id: 235,
            location: {
              id: 103,
              country: 'Sierra Leone',
              code: '00A',
              city: 'Freetown',
              state: '',
            },
          },
          bidcycle: {
            name: 'Demo BidCycle 2017-10-31 16:00:51.254762',
          },
        },
        bid_statistics: [
          {
            id: null,
            total_bids: 0,
            in_grade: 0,
            at_skill: 0,
            in_grade_at_skill: 0,
            has_handshake_offered: false,
            has_handshake_accepted: null,
          },
        ],
      },
      status: 'closed',
      draft_date: '2017-12-20',
      submitted_date: '2017-12-20',
      handshake_offered_date: '2017-12-20',
      handshake_accepted_date: '2017-12-20',
      handshake_declined_date: '2017-12-20',
      in_panel_date: '2017-12-20',
      scheduled_panel_date: '2017-12-20',
      approved_date: '2017-12-20',
      declined_date: '2017-12-20',
      closed_date: '2017-12-20',
      create_date: '2017-12-20',
      update_date: '2017-12-20',
      is_priority: true,
      reviewer: {
        username: 'woodwardw',
        first_name: 'Wendy',
        last_name: 'Woodward',
        email: 'woodwardw@state.gov',
        phone_number: '555-555-5555',
        is_cdo: false,
      },
    },
    {
      id: 2,
      user: 'rehmant',
      position_info: {
        id: 79,
        position: {
          id: 84,
          grade: '04',
          skill: 'SECURITY (2501)',
          position_number: '56001600',
          title: 'SPECIAL AGENT',
          create_date: '2006-09-20',
          update_date: '2017-06-08',
          bureau: '(AF) BUREAU OF AFRICAN AFFAIRS',
          post: {
            id: 195,
            location: {
              id: 103,
              country: 'Sierra Leone',
              code: '00A',
              city: 'Freetown',
              state: '',
            },
          },
          bidcycle: {
            name: 'Demo BidCycle 2017-10-31 16:00:51.254762',
          },
        },
        bid_statistics: [
          {
            id: null,
            total_bids: 0,
            in_grade: 0,
            at_skill: 0,
            in_grade_at_skill: 0,
            has_handshake_offered: false,
            has_handshake_accepted: null,
          },
        ],
      },
      status: 'closed',
      draft_date: '2017-12-20',
      submitted_date: '2017-12-20',
      handshake_offered_date: '2017-12-20',
      handshake_accepted_date: '2017-12-20',
      handshake_declined_date: '2017-12-20',
      in_panel_date: '2017-12-20',
      scheduled_panel_date: '2017-12-20',
      approved_date: '2017-12-20',
      declined_date: '2017-12-20',
      closed_date: '2017-12-20',
      create_date: '2017-12-20',
      update_date: '2017-12-20',
      is_priority: false,
      reviewer: {
        username: 'woodwardw',
        first_name: 'Wendy',
        last_name: 'Woodward',
        email: 'woodwardw@state.gov',
        phone_number: '555-555-5555',
        is_cdo: false,
      },
    },
  ],
};

export default bidListObject;
