const favoritesObject = {
  favorites: [
    {
      id: 12325,
      status: null,
      status_code: 'OP',
      ted: '2020-03-17T19:13:25.970000Z',
      posted_date: '2020-03-17T19:13:25.970000Z',
      availability: {
        availability: null,
        reason: null,
      },
      is_urgent_vacancy: false,
      is_volunteer: false,
      is_hard_to_fill: false,
      position: {
        id: null,
        grade: '06',
        skill: 'CONSULAR AFFAIRS (3001)',
        skill_code: '3001',
        bureau: '(CA) BUREAU OF CONSULAR AFFAIRS',
        organization: '(A) ASSISTANT SECRETARY FOR ADMINISTRATION',
        tour_of_duty: 'INDEFINITE',
        classifications: null,
        representation: null,
        availability: {
          availability: null,
          reason: null,
        },
        position_number: '00003026',
        title: 'OMS (COM)',
        is_overseas: null,
        is_highlighted: false,
        create_date: null,
        update_date: null,
        effective_date: null,
        posted_date: '2020-03-17T19:13:25.970000Z',
        description: {
          id: null,
          last_editing_user: null,
          is_editable_by_user: null,
          date_created: null,
          date_updated: '2020-03-17T09:13:25.710000Z',
          content: 'Incumbent is the Office Manager for the Ambassador at a greater hardship post with a staff of 21 direct-hire Americans and 120 FSNs. She supervises an FSN protocol assistant and COM driver. She manages the Ambassador&#39;s calendar, work and travel schedules. She backs up the direct-hire DCM OMS who supports the DCM and Pol/Econ officer and who backs up COM OMS position. POC: COM OMS Shaye Palmer via e-mail:  PalmerSA&#64;state.gov. or DCM OMS Joanne Schmoll via e-mail, SchmollJL&#64;state.gov; 232-22-515-102.  &#40;Revised 07/2015&#41; &#13;&#10;AF 360 CLC- http://appcenter.state.sbu/CLC',
          point_of_contact: null,
          website: null,
        },
        current_assignment: {
          user: null,
          tour_of_duty: 'INDEFINITE',
          status: null,
          start_date: null,
          estimated_end_date: '2012-10-22T05:00:00Z',
        },
        post: {
          id: null,
          code: 'PK4000000',
          tour_of_duty: 'INDEFINITE',
          post_overview_url: null,
          post_bidding_considerations_url: null,
          cost_of_living_adjustment: null,
          differential_rate: 25,
          danger_pay: 0,
          rest_relaxation_point: null,
          has_consumable_allowance: null,
          has_service_needs_differential: null,
          obc_id: null,
          location: {
            country: 'USA',
            code: 'PK4000000',
            city: 'Kenvil',
            state: 'Connecticut',
          },
        },
        latest_bidcycle: {
          id: 155,
          name: '2018 DCM/PO Cycle',
          cycle_start_date: null,
          cycle_deadline_date: null,
          cycle_end_date: null,
          active: null,
        },
        languages: [
          {
            language: 'Telugu',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Telugu (TE) 1/1',
          },
          {
            language: 'Czech',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Czech (CX) 1/1',
          },
        ],
      },
      bidcycle: {
        id: 155,
        name: '2018 DCM/PO Cycle',
        cycle_start_date: null,
        cycle_deadline_date: null,
        cycle_end_date: null,
        active: null,
      },
      bid_statistics: [
        {
          id: null,
          total_bids: null,
          in_grade: null,
          at_skill: null,
          in_grade_at_skill: null,
          has_handshake_offered: false,
          has_handshake_accepted: null,
        },
      ],
    },
    {
      id: 12330,
      status: null,
      status_code: 'OP',
      ted: '2020-03-17T19:13:25.970000Z',
      posted_date: '2020-03-17T19:13:25.970000Z',
      availability: {
        availability: null,
        reason: null,
      },
      is_urgent_vacancy: false,
      is_volunteer: false,
      is_hard_to_fill: false,
      position: {
        id: null,
        grade: 'OC',
        skill: 'REFUGEE AFFAIRS (6090)',
        skill_code: '6090',
        bureau: '(CSO) BUREAU OF CONFLICT AND STABILIZATION OPERATIONS',
        organization: '(A) ASSISTANT SECRETARY FOR ADMINISTRATION',
        tour_of_duty: '2 YRS (4 R & R)',
        classifications: null,
        representation: null,
        availability: {
          availability: null,
          reason: null,
        },
        position_number: '10034001',
        title: 'OMS (DCM)',
        is_overseas: null,
        is_highlighted: false,
        create_date: null,
        update_date: null,
        effective_date: null,
        posted_date: '2020-03-17T19:13:25.970000Z',
        description: {
          id: null,
          last_editing_user: null,
          is_editable_by_user: null,
          date_created: null,
          date_updated: '2020-03-17T09:13:25.710000Z',
          content: 'The Office Management Specialist &#40;OMS&#41; for the Deputy Chief of Mission &#40;DCM&#41; provides office management services in this Mission of six agencies, 387 American and Locally Employed Staff &#40;LES&#41; positions, and 279 guard force contractors.  The OMS manages Executive Office operations and positionstains the DCM&#8217;s calendar in support of overall Mission goals and objectives.  The OMS &#40;DCM&#41; drafts routine correspondence, memoranda and cables as appropriate and ensures documents are cleared and delivered in a timely fashion. The OMS serves as back up to the Ambassador&#8217;s OMS.  POCs areSandra McInturff, DCM OMS, McInturffSL&#64;state.gov, 231-77-677-7000, ext. 7452; Samue Watson, DCM, WatsonSR&#64;state.gov, 231-77-677-7000, ext. 7452. Please submit lobbying documents to the 360 Community Lobbying Center http://appcenter.state.sbu/CLC. &#40;Revised 1/2017&#41;&#13;&#10;&#13;&#10;',
          point_of_contact: null,
          website: null,
        },
        current_assignment: {
          user: null,
          tour_of_duty: '2 YRS (4 R & R)',
          status: null,
          start_date: null,
          estimated_end_date: '2012-10-22T05:00:00Z',
        },
        post: {
          id: null,
          code: 'SU4000000',
          tour_of_duty: '2 YRS (4 R & R)',
          post_overview_url: null,
          post_bidding_considerations_url: null,
          cost_of_living_adjustment: null,
          differential_rate: 15,
          danger_pay: 20,
          rest_relaxation_point: null,
          has_consumable_allowance: null,
          has_service_needs_differential: null,
          obc_id: null,
          location: {
            country: 'USA',
            code: 'SU4000000',
            city: 'Darbydale',
            state: 'Arizona',
          },
        },
        latest_bidcycle: {
          id: 155,
          name: '2018 DCM/PO Cycle',
          cycle_start_date: null,
          cycle_deadline_date: null,
          cycle_end_date: null,
          active: null,
        },
        languages: [
          {
            language: 'Somali',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Somali (SM) 1/1',
          },
          {
            language: 'Kirghiz',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Kirghiz (KM) 1/1',
          },
        ],
      },
      bidcycle: {
        id: 155,
        name: '2018 DCM/PO Cycle',
        cycle_start_date: null,
        cycle_deadline_date: null,
        cycle_end_date: null,
        active: null,
      },
      bid_statistics: [
        {
          id: null,
          total_bids: null,
          in_grade: null,
          at_skill: null,
          in_grade_at_skill: null,
          has_handshake_offered: false,
          has_handshake_accepted: null,
        },
      ],
    },
  ],
  favoritesPV: [
    {
      id: 5284,
      ted: '2012-10-22T05:00:00Z',
      bidcycle: {
        id: 12,
        name: 'Summer 2020',
        cycle_start_date: null,
        cycle_deadline_date: null,
        cycle_end_date: null,
        active: true,
      },
      position: {
        grade: '03',
        skill: 'ECON RESOURCES & COMMODITIES (5050)',
        bureau: '(DRL) OFF OF THE ASST SEC BUR OF DEMO, H R,  AND LABOR',
        organization: '(A) ASSISTANT SECRETARY FOR ADMINISTRATION',
        tour_of_duty: '1 YR (1 R & R)',
        languages: [
          {
            language: 'Chinese-Mandar',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Chinese-Mandar (CM) 1/1',
          },
          {
            language: 'Arabic Egyptian',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Arabic Egyptian (AE) 1/1',
          },
        ],
        post: {
          tour_of_duty: '1 YR (1 R & R)',
          post_overview_url: null,
          post_bidding_considerations_url: null,
          obc_id: null,
          differential_rate: 15,
          danger_pay: 25,
          location: {
            country: 'Russian Federation',
            code: 'UP3000000',
            city: 'Coral',
            state: '',
          },
        },
        current_assignment: {
          user: null,
          estimated_end_date: '2012-10-22T05:00:00Z',
        },
        position_number: '10059003',
        title: 'POLITICAL OFFICER',
        availability: {
          availability: true,
          reason: null,
        },
        bid_cycle_statuses: [
          {
            id: 5284,
            bidcycle: 'Summer 2020',
            position: 'POLITICAL OFFICER',
            status_code: null,
            status: null,
          },
        ],
        latest_bidcycle: {
          id: 12,
          name: 'Summer 2020',
          cycle_start_date: null,
          cycle_deadline_date: null,
          cycle_end_date: null,
          active: true,
        },
        description: {
          content: 'Internal Reporting Officer in a political section comprised of seven officers, one OMS, and three FSN political specialists.  Reports to the Political Counselor through the Deputy Counselor; supervises one FSN.  Monitors, analyzes, and reports on Saudi internal politics, including domestic policies and institutions, the Royal Family, Shura and Municipal Councils, tribes, and elections and political participation.  POC: John Godfrey &#40;godfreyjt&#64;state.gov&#41; and Abram Paley &#40;PaleyAW&#64;state.gov&#41;. This year NEA is once again collecting lobbying documents through its 360 Lobbying Center. Please submit your lobbying information at: http://appcenter.state.sbu/CLC. Also please send all inquiries and correspondence about this position to post at: saudibidders&#64;state.gov.',
          date_updated: '2020-03-17T09:13:25.710000Z',
        },
      },
      isPV: true,
    },
    {
      id: 5294,
      ted: '2012-02-02T05:00:00Z',
      bidcycle: {
        id: 12,
        name: 'Summer 2020',
        cycle_start_date: null,
        cycle_deadline_date: null,
        cycle_end_date: null,
        active: true,
      },
      position: {
        grade: '08',
        skill: 'DIPLOMATIC COURIER (2580)',
        bureau: '(BP) BUREAU OF BUDGET AND PLANNING',
        organization: '(A) ASSISTANT SECRETARY FOR ADMINISTRATION',
        tour_of_duty: '1 YEAR(2R&R)/HL/1 YEAR(2R&R)',
        languages: [
          {
            language: 'Hindi',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Hindi (HJ) 1/1',
          },
          {
            language: 'Arabic Modern',
            reading_proficiency: '1',
            spoken_proficiency: '1',
            representation: 'Arabic Modern (AD) 1/1',
          },
        ],
        post: {
          tour_of_duty: '1 YEAR(2R&R)/HL/1 YEAR(2R&R)',
          post_overview_url: null,
          post_bidding_considerations_url: null,
          obc_id: null,
          differential_rate: 10,
          danger_pay: 20,
          location: {
            country: 'USA',
            code: 'RS8900000',
            city: 'Saranap',
            state: 'Maine',
          },
        },
        current_assignment: {
          user: null,
          estimated_end_date: '2012-02-02T05:00:00Z',
        },
        position_number: '55007010',
        title: 'INFORMATION PROGRAMS OFFICER',
        availability: {
          availability: true,
          reason: null,
        },
        bid_cycle_statuses: [
          {
            id: 5294,
            bidcycle: 'Summer 2020',
            position: 'INFORMATION PROGRAMS OFFICER',
            status_code: null,
            status: null,
          },
        ],
        latest_bidcycle: {
          id: 12,
          name: 'Summer 2020',
          cycle_start_date: null,
          cycle_deadline_date: null,
          cycle_end_date: null,
          active: true,
        },
        description: {
          content: 'The IPO is one of three Information Management Specialists &#40;IMS&#41; at Post. The incumbent is in charge of the Information Program Center &#40;IPC&#41; providing oversight, management, and security for all classified computer system, radio and telephone operations at Embassy Harare. The employee supervises one USDH, one Information Management Assistant and eight locally employed staff &#40;LES&#41;. The IPO reports to the Information Management Officer &#40;IMO&#41;. POC IPO John Miller via unclassified e-mail or telephone number 263-4-250-593 ext. 4900, IVG 778-0000 or IMO Mark Myelle.  Please submit lobbying documents to the AF 360 CLC- http://appcenter.state.sbu/CLC. ',
          date_updated: '2020-03-17T09:13:25.710000Z',
        },
      },
      isPV: true,
    },
  ],
  counts: {
    favorites: 2,
    favoritesPV: 2,
    all: 4,
  },
};

export default favoritesObject;
