const resultsObject = {
  count: 2,
  results: [
    {
      id: 6,
      grade: '06',
      skill: 'OFFICE MANAGEMENT (9017)',
      bureau: '(AF) BUREAU OF AFRICAN AFFAIRS',
      organization: '(MONROVIA) MONROVIA LIBERIA',
      classifications: [],
      representation: '[10034001] OMS (DCM) (Monrovia, Liberia)',
      is_highlighted: false,
      position_number: '10034001',
      title: 'OMS (DCM)',
      is_overseas: true,
      create_date: '2006-09-20T00:00:00Z',
      update_date: '2017-06-08T00:00:00Z',
      effective_date: '2012-10-22T00:00:00Z',
      status_code: null,
      status: null,
      description: {
        id: 90,
        last_editing_user: null,
        is_editable_by_user: false,
        date_created: '2018-03-08T18:00:33.241370Z',
        date_updated: '2018-03-13T15:55:00.018644Z',
        content: 'The Office Management Specialist (OMS) for the Deputy Chief of Mission (DCM) provides office management services in this Mission of six agencies, 387 American and Locally Employed Staff (LES) positions, and 279 guard force contractors.  The OMS manages Executive Office operations and positionstains the DCM’s calendar in support of overall Mission goals and objectives.  The OMS (DCM) drafts routine correspondence, memoranda and cables as appropriate and ensures documents are cleared and delivered in a timely fashion. The OMS serves as back up to the Ambassador’s OMS.  POCs areSandra McInturff, DCM OMS, McInturffSL@state.gov, 231-77-677-7000, ext. 7452; Samue Watson, DCM, WatsonSR@state.gov, 231-77-677-7000, ext. 7452. Please submit lobbying documents to the 360 Community Lobbying Center http://appcenter.state.sbu/CLC. (Revised 1/2017)\r\n\r\n',
        point_of_contact: null,
        website: null,
      },
      tour_of_duty: null,
      current_assignment: {
        user: 'John Doe',
        tour_of_duty: '2 YRS (2 R & R)',
        status: 'active',
        start_date: '2018-03-13T15:51:11.478084Z',
        estimated_end_date: '2020-03-13T15:51:11.478084Z',
      },
      post: {
        id: 160,
        code: 'LI6000000',
        location: 'Monrovia, Liberia',
        tour_of_duty: '2 YRS (2 R & R)',
        cost_of_living_adjustment: 30,
        differential_rate: 30,
        danger_pay: 0,
        rest_relaxation_point: 'Paris',
        has_consumable_allowance: true,
        has_service_needs_differential: true,
        obc_id: null,
      },
      languages: [],
      bid_statistics: [
        {
          id: 6,
          bidcycle: 'Demo BidCycle 2018-03-13 15:51:10.980576+00:00',
          total_bids: 2,
          in_grade: 0,
          at_skill: 0,
          in_grade_at_skill: 0,
        },
      ],
      latest_bidcycle: {
        id: 1,
        name: 'Demo BidCycle 2018-03-13 15:51:10.980576+00:00',
        cycle_start_date: '2017-12-13T15:51:10.980554Z',
        cycle_deadline_date: '2018-04-13T15:51:10.980554Z',
        cycle_end_date: '2018-06-13T15:51:10.980554Z',
        active: true,
      },
    },
    {
      id: 60,
      grade: '04',
      skill: 'SECURITY (2501)',
      bureau: '(WHA) BUREAU OF WESTERN HEMISPHERIC AFFAIRS',
      organization: '(PORT AU PRIN) PORT AU PRINCE HAITI',
      classifications: [],
      representation: '[56082000] SPECIAL AGENT (Port-Au-Prince, Haiti)',
      is_highlighted: false,
      position_number: '56082000',
      title: 'SPECIAL AGENT',
      is_overseas: true,
      create_date: '2006-09-20T00:00:00Z',
      update_date: '2017-06-08T00:00:00Z',
      effective_date: '2016-10-02T00:00:00Z',
      status_code: null,
      status: null,
      description: {
        id: 26,
        last_editing_user: null,
        is_editable_by_user: false,
        date_created: '2018-03-08T18:00:32.971745Z',
        date_updated: '2018-03-13T15:54:59.677323Z',
        content: '(updated August 2012) The incumbent serves as one of four Assistant Regional Security Officers (ARSO) in the Regional Security Office in a two year assignment with a rotating management portfolio that provides generous exposure to all aspects of Diplomatic Security’s overseas programs. RSO Port-au-Prince currently consists of a 6 member Marine Security Guard Detachment, 750+direct hire Mission guard force, 17 direct-hire Bodyguards, 2 FSN Investigators, 6 member Surveillance Detection Team, a 2-person Residential Security Unit, and one Office Management Specialist.  The incumbent has direct supervisory responsibilities.  The incumbent is expected to manage the Marine Security Guard program, Mission residential and physical security programs, operational and administrative oversight of the direct hire Mission guard force, and complex budget issues. The incumbent also coordinates security for large-scale Mission events and visiting high ranking USG officials and conducts personnel, terrorist, criminal, and counterintelligence investigations as required. Point of Contact is RSO Jeffrey M. Roberts.',
        point_of_contact: null,
        website: null,
      },
      tour_of_duty: null,
      current_assignment: {
        user: 'John Doe',
        tour_of_duty: '2 YRS (2 R & R)',
        status: 'active',
        start_date: '2018-03-13T15:51:13.126727Z',
        estimated_end_date: '2020-03-13T15:51:13.126727Z',
      },
      post: {
        id: 110,
        code: 'HA7000000',
        location: 'Port-Au-Prince, Haiti',
        tour_of_duty: '2 YRS (2 R & R)',
        cost_of_living_adjustment: 15,
        differential_rate: 20,
        danger_pay: 15,
        rest_relaxation_point: 'Miami',
        has_consumable_allowance: true,
        has_service_needs_differential: true,
        obc_id: null,
      },
      languages: [
        {
          id: 1,
          language: 'French (FR)',
          reading_proficiency: '2',
          spoken_proficiency: '2',
          representation: 'French (FR) 2/2',
        },
        {
          id: 20,
          language: 'Haitian Creole (HC)',
          reading_proficiency: '0',
          spoken_proficiency: '0',
          representation: 'Haitian Creole (HC) 0/0',
        },
      ],
      bid_statistics: [
        {
          id: 60,
          bidcycle: 'Demo BidCycle 2018-03-13 15:51:10.980576+00:00',
          total_bids: 0,
          in_grade: 0,
          at_skill: 0,
          in_grade_at_skill: 0,
        },
      ],
      latest_bidcycle: {
        id: 1,
        name: 'Demo BidCycle 2018-03-13 15:51:10.980576+00:00',
        cycle_start_date: '2017-12-13T15:51:10.980554Z',
        cycle_deadline_date: '2018-04-13T15:51:10.980554Z',
        cycle_end_date: '2018-06-13T15:51:10.980554Z',
        active: true,
      },
    },
  ],
};

export default resultsObject;
