import {
  jobCategoriesAdminFetchData,
  jobCategoriesAdminFetchDataErrored,
  jobCategoriesAdminFetchDataIsLoading,
  jobCategoriesDeleteCatHasErrored,
  jobCategoriesDeleteCatIsLoading,
  jobCategoriesDeleteCatSuccess,
  jobCategoriesEditCatHasErrored,
  jobCategoriesEditCatIsLoading,
  jobCategoriesEditCatSuccess,
  jobCategoriesFetchSkills,
  jobCategoriesFetchSkillsHasErrored,
  jobCategoriesFetchSkillsIsLoading,
  jobCategoriesSaveNewCatHasErrored,
  jobCategoriesSaveNewCatIsLoading,
  jobCategoriesSaveNewCatSuccess,
} from './jobCategories';

export default {
  jobCategoriesAdminFetchDataErrored,
  jobCategoriesAdminFetchDataIsLoading,
  jobCategoriesAdminFetchData,
  jobCategoriesDeleteCatHasErrored,
  jobCategoriesDeleteCatIsLoading,
  jobCategoriesDeleteCatSuccess,
  jobCategoriesEditCatHasErrored,
  jobCategoriesEditCatIsLoading,
  jobCategoriesEditCatSuccess,
  jobCategoriesFetchSkills,
  jobCategoriesFetchSkillsHasErrored,
  jobCategoriesFetchSkillsIsLoading,
  jobCategoriesSaveNewCatHasErrored,
  jobCategoriesSaveNewCatIsLoading,
  jobCategoriesSaveNewCatSuccess,
};
