import {
  assignmentCycle,
  assignmentCycleFetchDataErrored,
  assignmentCycleFetchDataLoading,
  assignmentCycleSelections,
  cycleManagement,
  cycleManagementFetchDataErrored,
  cycleManagementFetchDataLoading,
  cycleManagementSelections,
  cyclePositionEditHasErrored,
  cyclePositionEditIsLoading,
  cyclePositionEditSuccess,
  cyclePositionRemoveHasErrored,
  cyclePositionRemoveIsLoading,
  cyclePositionRemoveSuccess,
  cyclePositionSearch,
  cyclePositionSearchFetchDataErrored,
  cyclePositionSearchFetchDataLoading,
  cyclePositionSearchSelections,


} from './cycleManagement';

export default {
  assignmentCycle,
  assignmentCycleFetchDataErrored,
  assignmentCycleFetchDataLoading,
  assignmentCycleSelections,
  cycleManagement,
  cycleManagementFetchDataErrored,
  cycleManagementFetchDataLoading,
  cycleManagementSelections,
  cyclePositionEditHasErrored,
  cyclePositionEditIsLoading,
  cyclePositionEditSuccess,
  cyclePositionRemoveIsLoading,
  cyclePositionRemoveHasErrored,
  cyclePositionRemoveSuccess,
  cyclePositionSearch,
  cyclePositionSearchFetchDataErrored,
  cyclePositionSearchFetchDataLoading,
  cyclePositionSearchSelections,
};
