import {
  cycleCategories,
  cycleCategoriesErrored,
  cycleCategoriesLoading,
  cycleCategorySelection,
  cycleJobCategories,
  cycleJobCategoriesEdit,
  cycleJobCategoriesEditErrored,
  cycleJobCategoriesEditLoading,
  cycleJobCategoriesErrored,
  cycleJobCategoriesLoading,
  cycleJobCategoriesStatuses,
  cycleJobCategoriesStatusesErrored,
  cycleJobCategoriesStatusesLoading,
} from './cycleJobCategories';

export default {
  cycleCategories,
  cycleCategoriesErrored,
  cycleCategoriesLoading,
  cycleCategorySelection,
  cycleJobCategories,
  cycleJobCategoriesEdit,
  cycleJobCategoriesEditErrored,
  cycleJobCategoriesEditLoading,
  cycleJobCategoriesErrored,
  cycleJobCategoriesLoading,
  cycleJobCategoriesStatuses,
  cycleJobCategoriesStatusesErrored,
  cycleJobCategoriesStatusesLoading,
};
