import {
  projectedVacancy,
  projectedVacancyAddToProposedCycle,
  projectedVacancyAddToProposedCycleErrored,
  projectedVacancyAddToProposedCycleLoading,
  projectedVacancyEdit,
  projectedVacancyEditErrored,
  projectedVacancyEditLoading,
  projectedVacancyFetchDataErrored,
  projectedVacancyFetchDataLoading,
  projectedVacancyFilters,
  projectedVacancyFiltersFetchDataErrored,
  projectedVacancyFiltersFetchDataLoading,
  projectedVacancySelections,
} from './projectedVacancy';

export default {
  projectedVacancy,
  projectedVacancyAddToProposedCycle,
  projectedVacancyAddToProposedCycleErrored,
  projectedVacancyAddToProposedCycleLoading,
  projectedVacancyEdit,
  projectedVacancyEditErrored,
  projectedVacancyEditLoading,
  projectedVacancyFetchDataErrored,
  projectedVacancyFetchDataLoading,
  projectedVacancyFilters,
  projectedVacancyFiltersFetchDataErrored,
  projectedVacancyFiltersFetchDataLoading,
  projectedVacancySelections,
};
