import {
  projectedVacancy,
  projectedVacancyEdit,
  projectedVacancyEditCapsuleDesc,
  projectedVacancyEditCapsuleDescErrored,
  projectedVacancyEditCapsuleDescLoading,
  projectedVacancyEditErrored,
  projectedVacancyEditLangOffsets,
  projectedVacancyEditLangOffsetsErrored,
  projectedVacancyEditLangOffsetsLoading,
  projectedVacancyEditLoading,
  projectedVacancyFetchDataErrored,
  projectedVacancyFetchDataLoading,
  projectedVacancyFilters,
  projectedVacancyFiltersErrored,
  projectedVacancyFiltersLoading,
  projectedVacancyLanguageOffsets,
  projectedVacancyLanguageOffsetsErrored,
  projectedVacancyLanguageOffsetsLoading,
  projectedVacancySelections,
} from './projectedVacancy';

export default {
  projectedVacancy,
  projectedVacancyEdit,
  projectedVacancyEditCapsuleDesc,
  projectedVacancyEditCapsuleDescErrored,
  projectedVacancyEditCapsuleDescLoading,
  projectedVacancyEditErrored,
  projectedVacancyEditLangOffsets,
  projectedVacancyEditLangOffsetsErrored,
  projectedVacancyEditLangOffsetsLoading,
  projectedVacancyEditLoading,
  projectedVacancyFetchDataErrored,
  projectedVacancyFetchDataLoading,
  projectedVacancyFilters,
  projectedVacancyFiltersErrored,
  projectedVacancyFiltersLoading,
  projectedVacancyLanguageOffsets,
  projectedVacancyLanguageOffsetsErrored,
  projectedVacancyLanguageOffsetsLoading,
  projectedVacancySelections,
};
