import {
  projectedVacancy,
  projectedVacancyFetchDataErrored,
  projectedVacancyFetchDataLoading,
  projectedVacancyFilters,
  projectedVacancyFiltersErrored,
  projectedVacancyFiltersLoading,
  projectedVacancyLangOffsetOptions,
  projectedVacancyLangOffsetOptionsErrored,
  projectedVacancyLangOffsetOptionsLoading,
  projectedVacancyLangOffsets,
  projectedVacancyLangOffsetsErrored,
  projectedVacancyLangOffsetsLoading,
  projectedVacancySelections,
} from './projectedVacancy';

export default {
  projectedVacancy,
  projectedVacancyFetchDataErrored,
  projectedVacancyFetchDataLoading,
  projectedVacancyFilters,
  projectedVacancyFiltersErrored,
  projectedVacancyFiltersLoading,
  projectedVacancyLangOffsetOptions,
  projectedVacancyLangOffsetOptionsErrored,
  projectedVacancyLangOffsetOptionsLoading,
  projectedVacancyLangOffsets,
  projectedVacancyLangOffsetsErrored,
  projectedVacancyLangOffsetsLoading,
  projectedVacancySelections,
};
